---
- name: Get Device Facts
  hosts: all
  roles:
    - Juniper.junos
  gather_facts: no
  connection: local

  tasks:
    - name: Retrieve facts from device running Junos OS
      juniper_junos_facts:
    - name: Print version
      debug:
        var: junos.version
