---
- name: Get Device Facts
  hosts: all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: yes

  tasks:
    - name: Retrieve facts from device running Junos OS
      juniper_junos_facts:
        host: "{{ inventory_hostname }}"
        savedir: "{{ playbook_dir }}"
    - name: Print version
      debug:
        var: junos.version
