---
- name: Run local expect script via shell
  hosts: all
  gather_facts: no

  tasks:
  - name: Run local expect script via shell
    command: expect ./ts_show.tcl 10.88.241.1 {{ ip }}
    register: response
  - name: "Print result"
    debug:
      var: response

